- name: Verify docker is installed
  ansible.builtin.command: docker --version
  register: docker_version
  changed_when: false

- name: Show version 
  ansible.builtin.debug:
    msg: "{{docker_version.stdout}}"